name: PHP Native CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check PHP Syntax Errors (Lint)
      run: |
        find . -name "*.php" -exec php -l {} \; | grep -v "No syntax errors detected" && exit 1 || true