name: PHP Native CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivamathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, mysqli, pdo_mysql

    - name: Check PHP Syntax Errors (Lint)
      run: |
